attributes:
  - name: "x"
    compression_type: 1 # [vector quantization: 0, scalar quantization: 1, huffman coding: 2]
    type: "float"
    components: 1

  - name: "y"
    compression_type: 1
    type: "float"
    components: 1

  - name: "z"
    compression_type: 1
    type: "float"
    components: 1

  - name: "nx"
    compression_type: 1
    type: "float"
    components: 1

  - name: "ny"
    compression_type: 1
    type: "float"
    components: 1

  - name: "nz"
    compression_type: 1
    type: "float"
    components: 1

  # sh_coeff, all coefficient of Spherical harmonic
  - name: "sh_coeff"
    compression_type: 0
    type: "float"
    components: 48

  # scalar attributes which are not vectors
  - name: "opacity"
    compression_type: 1
    type: "float"
    components: 1

  - name: "scale_0"
    compression_type: 1
    type: "float"
    components: 1

  - name: "scale_1"
    compression_type: 1
    type: "float"
    components: 1

  - name: "scale_2"
    compression_type: 1
    type: "float"
    components: 1

  - name: "rot_0"
    compression_type: 1
    type: "float"
    components: 1

  - name: "rot_1"
    compression_type: 1
    type: "float"
    components: 1

  - name: "rot_2"
    compression_type: 1
    type: "float"
    components: 1

  - name: "rot_3"
    compression_type: 1
    type: "float"
    components: 1
